"""
Django settings for jbl_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jmbq^j0&fs_m465i_=%2^8skyb2318c7&bx3az!tqzr84naq*)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'apps.league',
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jbl_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.league.context_processors.site_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'jbl_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

"""
Django settings for jbl_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jmbq^j0&fs_m465i_=%2^8skyb2318c7&bx3az!tqzr84naq*)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'apps.league',
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jbl_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.league.context_processors.site_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'jbl_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'new_jbl',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Mapea los niveles de django.contrib.messages a clases de alerta de Bootstrap 5
MESSAGE_TAGS = {
    10: 'secondary',   # DEBUG
    20: 'info',        # INFO
    25: 'success',     # SUCCESS
    30: 'warning',     # WARNING
    40: 'danger',      # ERROR
}

LOGIN_URL = '/league/login/'
LOGIN_REDIRECT_URL = '/league/'
LOGOUT_REDIRECT_URL = '/league/'

# Datos que se muestran en el footer de todas las páginas.
# TODO: Reemplaza estos valores con los datos reales del equipo y la materia.
SITE_DEVELOPERS = ['Nombre Apellido 1', 'Nombre Apellido 2']
SITE_COURSE_NAME = 'Nombre de la Materia'
SITE_YEAR = 2026

# Nombre e información pública de la liga (usada en el dashboard público)
LEAGUE_NAME = 'Junior Baseball League'
LEAGUE_SPORT = 'Béisbol Infantil y Juvenil'
LEAGUE_FOUNDED_YEAR = 2024
LEAGUE_DESCRIPTION = (
    'Liga comunitaria de béisbol para categorías Starter (6-9), '
    'Junior (10-13) y Upper (14-17), dedicada a fomentar el deporte, '
    'el trabajo en equipo y los valores en niños y jóvenes.'
)

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'new_jbl',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Mapea los niveles de django.contrib.messages a clases de alerta de Bootstrap 5
MESSAGE_TAGS = {
    10: 'secondary',   # DEBUG
    20: 'info',        # INFO
    25: 'success',     # SUCCESS
    30: 'warning',     # WARNING
    40: 'danger',      # ERROR
}

LOGIN_URL = '/league/login/'
LOGIN_REDIRECT_URL = '/league/'
LOGOUT_REDIRECT_URL = '/league/'

# Datos que se muestran en el footer de todas las páginas.
# TODO: Reemplaza estos valores con los datos reales del equipo y la materia.
SITE_DEVELOPERS = ['Nombre Apellido 1', 'Nombre Apellido 2']
SITE_COURSE_NAME = 'Nombre de la Materia'
SITE_YEAR = 2026

# Nombre e información pública de la liga (usada en el dashboard público)
LEAGUE_NAME = 'Junior Baseball League'
LEAGUE_SPORT = 'Béisbol Infantil y Juvenil'
LEAGUE_FOUNDED_YEAR = 2024
LEAGUE_DESCRIPTION = (
    'Liga comunitaria de béisbol para categorías Starter (6-9), '
    'Junior (10-13) y Upper (14-17), dedicada a fomentar el deporte, '
    'el trabajo en equipo y los valores en niños y jóvenes.'
)

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

